# Generated by Django 5.2.1 on 2025-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'student'), ('Teacher', 'teacher')], default='student', max_length=10),
        ),
    ]
